//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Number { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public decimal Sub_Total { get; set; }
        public string Code_Product { get; set; }
        public int Id_Client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
    }
}
